### ISSUE TITLE
Add possibility to set variables from environment or config file

### ISSUE THREAD

**Issue by Le0nRoy** [nickosh/asst#1]
```
Start a server with python3 server/asst/main.py or use Dockerfile. It will start on 5000 port. It can be changed in main.py - SERVER_PORT = 5000 and inside a Dockerfile - EXPOSE 5000.
```
If we have any variables such as above we shall move them to some type of config file so that user could change them without opening source code

**Comment by nickosh** [comment]
You are right. Was a little lazy about this one - just one param. But still must be done properly.
